# Generated by Django 5.2.6 on 2025-09-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_data',
            name='book_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='book_data',
            name='book_description',
            field=models.TextField(default=''),
        ),
    ]
