# Generated by Django 5.2.6 on 2025-09-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pages", "0002_book_data_book_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("user_email", models.EmailField(max_length=200)),
                ("user_password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
