# Generated by Django 5.2.6 on 2025-09-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pages", "0003_user_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_data",
            name="id",
        ),
        migrations.AddField(
            model_name="user_data",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
