# Generated by Django 5.2.6 on 2025-09-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pages", "0004_remove_user_data_id_user_data_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart_Data",
            fields=[
                ("user_name", models.CharField(max_length=100)),
                ("cart_itemId", models.AutoField(primary_key=True, serialize=False)),
                ("cart_itemName", models.CharField(max_length=100)),
                ("cart_itemPrice", models.FloatField(default=0.0)),
                ("cart_itemDes", models.TextField(default="")),
            ],
            options={
                "db_table": "Cart",
            },
        ),
    ]
